spring:
  application:
    name: "cicd"
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
        dialect:
          nodeValue: org.hibernate.dialect.MySQL8Dialect
          storage_engine: innodb
        generate_statistics: 'true'
        format_sql: 'true'
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    password: '1234'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'root'
    url: 'jdbc:mysql://localhost:3306/cicd?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true'