name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Java CI with Gradle"]
    types: [completed]

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Server
      env:
        SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
        SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
      run: |
        scp -P $SERVER_PORT ./build/libs/*.jar $SERVER_USERNAME@$SERVER_ADDRESS:~/cicd
        # 추가로 필요한 배포 작업 수행
