name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Java CI with Gradle"]
    types: [completed]

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Server
      env:
        SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
        SERVER_HOST_KEY: ${{ secrets.SERVER_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SERVER_HOST_KEY" > ~/.ssh/known_hosts
        sshpass -p "$SERVER_PASSWORD" scp -P 522 -o StrictHostKeyChecking=accept-new *.jar $SERVER_USERNAME@$SERVER_ADDRESS:~/cicd


